In [8]:
import mxnet.image as image
import numpy as np
import mxnet as mx

In [2]:
# SSD 
pikachu = image.ImageDetIter(batch_size=32, 
                               data_shape=(3, 256, 256), 
                               path_imgrec="../../pikachu/Pikachu/data/pikachu_train.rec", 
                               shuffle=False)

In [7]:
batch = pikachu.next()
print batch.data[0].shape
print batch.label[0].shape

(32L, 3L, 256L, 256L)
(32L, 1L, 5L)


In [11]:
batch.label[0][:10]
(1,100,5)


[[[ 0.          0.52174443  0.39983985  0.60991675  0.52888846]]

 [[ 0.          0.49537563  0.37465474  0.60650802  0.50124604]]

 [[ 0.          0.36016801  0.40356323  0.47823539  0.55117148]]

 [[ 0.          0.59086055  0.29776123  0.7365272   0.4734301 ]]

 [[ 0.          0.41089383  0.39647639  0.49731091  0.53626442]]

 [[ 0.          0.36045885  0.29452375  0.50003248  0.44324386]]

 [[ 0.          0.34180146  0.3637726   0.42967331  0.48979521]]

 [[ 0.          0.30706233  0.29764614  0.4224554   0.44424239]]

 [[ 0.          0.28417715  0.34752172  0.384413    0.51528209]]

 [[ 0.          0.34698078  0.39938366  0.48452142  0.57232022]]]
<NDArray 10x1x5 @cpu(0)>

In [ ]:
[c x y w h + class]
0<x,y<1